language: bash
services: docker

env:
  - VERSION=jdk8
  - VERSION=jdk11

before_install:
  - env | sort
  - cd "${VERSION}${VARIANT:+-$VARIANT}"
  - image="gradle:${VERSION}${VARIANT:+-$VARIANT}"
  - docker rmi "${image}" || true
  - docker images --quiet --filter=dangling=true | xargs --no-run-if-empty docker rmi -f
  - docker images --format "table {{.Repository}}:{{.Tag}}" | tail --lines=+2 | grep "corretto" | xargs --no-run-if-empty --max-lines=1 docker pull

install:
  - docker build --tag "${image}" .

script:
  - cd ../test
  - ./run.sh "${image}" "6.3"
